name: CI

on: [push, pull_request, fork, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install .
          pip install ruff watchfiles
          npm install -g pyright

      - name: Check code quality
        run: |
          ruff check --output-format github
          ruff format --check --diff

      - name: Show possible enhancements
        run: |
          ruff check --select ALL --exit-zero --unsafe-fixes --output-format github
          ruff check --select ALL --exit-zero --unsafe-fixes --diff

      - name: Check types
        run: |
          pyright --version
          pyright --stats

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12

      - name: Build package
        run: |
          pdm build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: [lint, build]
    permissions:
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print-hash: true
          verbose: true
